spring.application.name=FindPlaces

# server config
server.port = ${SERVER_PORT:9090}

# db config
spring.datasource.driver_class_name = org.postgresql.Driver
spring.datasource.url = ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/community_map}
spring.datasource.username = ${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password = ${SPRING_DATASOURCE_PASSWORD:root}

# jpa config
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.show-sql = true

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#jwt
app.jwt.secret=change-this-to-a-very-long-random-secret-key-12345678901234567890
app.jwt.expiration=86400000

#image uploads config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:uploads/

# -----------------------------
# CUSTOM PROJECT PATHS
# -----------------------------
file.upload-dir=uploads/places


# -----------------------------
# LOGGING (OPTIONAL BUT USEFUL)
# -----------------------------
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE